value_int = int(10)
value_float = float(8.4)
value_str = str("No")
big_int = (value_int*3.5)
print ("big_int ", big_int)
value_float = (value_float - 1)
print ("value_float ", value_float)
print (value_int/value_float)
print (big_int/value_float)
value_str = ((value_str*2)+(3*"Yes"))
print (value_str)
